services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - langslate-network
    restart: unless-stopped

  langslate-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/langslate-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/langslate/data
      - uploads:/home/langslate/uploads
      - ./config.toml:/home/langslate/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - langslate-network
    restart: unless-stopped

  langslate-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: itzcrazykns1337/langslate-frontend:main
    depends_on:
      - langslate-backend
    ports:
      - 3000:3000
    networks:
      - langslate-network
    restart: unless-stopped

networks:
  langslate-network:

volumes:
  backend-dbstore:
  uploads:
